export const STORE_TYPES = {
    GET_STORE_LIST: 'GET_STORE_LIST',
    GET_STORE_BY_ID: 'GET_STORE_BY_ID',
    FETCH_STORE_LIST_REQUEST: 'FETCH_STORE_LIST_REQUEST',
    FETCH_STORE_LIST_FAILURE: 'FETCH_STORE_LIST_FAILURE'
};