/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pjlx911PC
 */
public class Workers extends javax.swing.JFrame {
    
    Connection conn;
    Statement state;
    ResultSet result;
    int currRow = 0;

    /**
     * Creates new form Workers
     */
    public Workers() {
        initComponents();
        DoConnect();
    }
    
    public void DoConnect(){
        
        try{
            //DB connection and variables
            String host = "jdbc:derby:C:/Users/pjlx911PC/.netbeans-derby/Employees";
            String uName = "user1";
            String uPW = "password";
            conn = DriverManager.getConnection(host, uName, uPW);
            
            //Load SQL elements into a ResultsSet
            state = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_UPDATABLE);
            String SQL = "SELECT * FROM WORKERS";
            result = state.executeQuery(SQL);
            
            //Move cursor and get the 1st record
            result.next();
            int colID = result.getInt("ID");
            String id = Integer.toString(colID);
            String firstN = result.getString("FIRST_NAME");
            String lastN = result.getString("LAST_NAME");
            String job = result.getString("JOB_TITLE");
            
            //Display the 1st record in the form fields
            txtID.setText(id);
            txtFirstName.setText(firstN);
            txtLastName.setText(lastN);
            txtJobTitle.setText(job);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJobTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNewRec = new javax.swing.JButton();
        btnSaveNewRec = new javax.swing.JButton();
        btnCanNewRec = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInfo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jButton3.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database UI");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtID.setText("id");

        txtFirstName.setText("FirstName");

        txtLastName.setText("LastName");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");

        txtJobTitle.setText("JobTitle");
        txtJobTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobTitleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Job Title");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(txtJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnLast)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUpdate.setText("Update Record");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNewRec.setText("New Record");
        btnNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecActionPerformed(evt);
            }
        });

        btnSaveNewRec.setText("Save New Record");
        btnSaveNewRec.setEnabled(false);
        btnSaveNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewRecActionPerformed(evt);
            }
        });

        btnCanNewRec.setText("Cancel New Record");
        btnCanNewRec.setEnabled(false);
        btnCanNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanNewRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnSaveNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCanNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNewRec))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveNewRec)
                    .addComponent(btnCanNewRec))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuInfo.setText("File");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuInfo.add(jMenuItem1);

        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobTitleActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        try{
            //Show next record, else end of file, show previous
            if(result.next())
            {
                 int colID = result.getInt("ID");
                String id = Integer.toString(colID);
                String firstN = result.getString("FIRST_NAME");
                String lastN = result.getString("LAST_NAME");
                String job = result.getString("JOB_TITLE");

                //Display the 1st record in the form fields
                txtID.setText(id);
                txtFirstName.setText(firstN);
                txtLastName.setText(lastN);
                txtJobTitle.setText(job);
            }
            else
            {
                result.previous();
                JOptionPane.showMessageDialog(Workers.this, "End of File");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(Workers.this, e.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        try{
            //Show last record, else end of file, show previous
            if(result.previous())
            {
                 int colID = result.getInt("ID");
                String id = Integer.toString(colID);
                String firstN = result.getString("FIRST_NAME");
                String lastN = result.getString("LAST_NAME");
                String job = result.getString("JOB_TITLE");

                //Display the 1st record in the form fields
                txtID.setText(id);
                txtFirstName.setText(firstN);
                txtLastName.setText(lastN);
                txtJobTitle.setText(job);
            }
            else
            {
                result.next();
                JOptionPane.showMessageDialog(Workers.this, "Start of File");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(Workers.this, e.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
         try{
            //Show the first record in the DB
            result.first();
            int colID = result.getInt("ID");
            String id = Integer.toString(colID);
            String firstN = result.getString("FIRST_NAME");
            String lastN = result.getString("LAST_NAME");
            String job = result.getString("JOB_TITLE");

            //Display the 1st record in the form fields
            txtID.setText(id);
            txtFirstName.setText(firstN);
            txtLastName.setText(lastN);
            txtJobTitle.setText(job);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(Workers.this, e.getMessage());
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
          try{
            //Show the last record in the DB
            result.last();
            int colID = result.getInt("ID");
            String id = Integer.toString(colID);
            String firstN = result.getString("FIRST_NAME");
            String lastN = result.getString("LAST_NAME");
            String job = result.getString("JOB_TITLE");

            //Display the 1st record in the form fields
            txtID.setText(id);
            txtFirstName.setText(firstN);
            txtLastName.setText(lastN);
            txtJobTitle.setText(job);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(Workers.this, e.getMessage());
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         try{
            //Get the variables text
            String firstN = txtFirstName.getText();
            String lastN = txtLastName.getText();
            String job = txtJobTitle.getText();
            String id = txtID.getText();
            //IF we want to update the ID of the record
            int newID = Integer.parseInt(id);
            //Update record and row
            result.updateInt("ID", newID);
            result.updateString("FIRST_NAME", firstN);
            result.updateString("LAST_NAME", lastN);
            result.updateString("JOB_TITLE", job);
            result.updateRow();
            JOptionPane.showMessageDialog(Workers.this, "Record Updated!");
         }
         catch(SQLException e)
         {
             JOptionPane.showMessageDialog(Workers.this, e.getMessage());
         }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecActionPerformed
        try {
            // TODO add your handling code here:
            //Get the current row (so it pulls up the correct record if cancelled)
            currRow = result.getRow();
            txtFirstName.setText("");
            txtLastName.setText("");
            txtJobTitle.setText("");
            txtID.setText("");
            
             //Disable all the buttons except Save and Cancel
            btnFirst.setEnabled(false);
            btnLast.setEnabled(false);
            btnPrevious.setEnabled(false);
            btnNext.setEnabled(false);

            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            btnNewRec.setEnabled(false);

            btnSaveNewRec.setEnabled(true);
            btnCanNewRec.setEnabled(true);
        } 
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(Workers.this, e.getMessage());
        }
    }//GEN-LAST:event_btnNewRecActionPerformed

    private void btnCanNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanNewRecActionPerformed
        try {
            // TODO add your handling code here:
            //Enable all the buttons except Save and Cancel
            
            //Set the row to the absolute row and set the fields
            result.absolute(currRow);
            txtFirstName.setText(result.getString("FIRST_NAME"));
            txtLastName.setText(result.getString("LAST_NAME"));
            txtJobTitle.setText(result.getString("JOB_TITLE"));
            txtID.setText(Integer.toString(result.getInt("ID")));
            
            //Disable all the buttons except Save and Cancel
            btnFirst.setEnabled(false);
            btnLast.setEnabled(false);
            btnPrevious.setEnabled(false);
            btnNext.setEnabled(false);
            btnFirst.setEnabled(true);
            btnLast.setEnabled(true);
            btnPrevious.setEnabled(true);
            btnNext.setEnabled(true);
            
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnNewRec.setEnabled(true);
            
            btnSaveNewRec.setEnabled(false);
            btnCanNewRec.setEnabled(false);
        } 
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(Workers.this, e.getMessage());
        }
    }//GEN-LAST:event_btnCanNewRecActionPerformed

    private void btnSaveNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewRecActionPerformed
        
        //Get the variables text
            String firstN = txtFirstName.getText();
            String lastN = txtLastName.getText();
            String job = txtJobTitle.getText();
            String id = txtID.getText();
            //IF we want to update the ID of the record
            int newID = Integer.parseInt(id);
        
        try {
            // TODO add your handling code here:
            //Move to new row
            result.moveToInsertRow();
            //Set that record's columns with these values & insert
            result.updateInt("ID", newID);
            result.updateString("FIRST_NAME", firstN);
            result.updateString("LAST_NAME", lastN);
            result.updateString("JOB_TITLE", job);
            
            result.insertRow();
            //Close off and comit changes to our DB
            state.close();
            result.close();
            
            //Load SQL elements into a ResultsSet
            state = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_UPDATABLE);
            String SQL = "SELECT * FROM WORKERS";
            result = state.executeQuery(SQL);
            
            //Move cursor and get the 1st record
            result.next();
            int colID = result.getInt("ID");
            String id2= Integer.toString(colID);
            String firstN2 = result.getString("FIRST_NAME");
            String lastN2 = result.getString("LAST_NAME");
            String job2 = result.getString("JOB_TITLE");
            
            //Display the 1st record in the form fields
            txtID.setText(id2);
            txtFirstName.setText(firstN2);
            txtLastName.setText(lastN2);
            txtJobTitle.setText(job2);
            
            //Disable all the buttons except Save and Cancel
            btnFirst.setEnabled(false);
            btnLast.setEnabled(false);
            btnPrevious.setEnabled(false);
            btnNext.setEnabled(false);
            btnFirst.setEnabled(true);
            btnLast.setEnabled(true);
            btnPrevious.setEnabled(true);
            btnNext.setEnabled(true);
            
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnNewRec.setEnabled(true);
            
            btnSaveNewRec.setEnabled(false);
            btnCanNewRec.setEnabled(false);
            
            JOptionPane.showMessageDialog(Workers.this, "New Record Saved!");            
        } 
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(Workers.this, e.getMessage());
        }
    }//GEN-LAST:event_btnSaveNewRecActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            // TODO add your handling code here:
            //deletes the current row
            result.deleteRow();
            
            //Close off and comit changes to our DB
            state.close();
            result.close();
                    
            //Load SQL elements into a ResultsSet
            state = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_UPDATABLE);
            String SQL = "SELECT * FROM WORKERS";
            result = state.executeQuery(SQL);
            
            //Move cursor and get the 1st record
            result.next();
            int colID = result.getInt("ID");
            String id = Integer.toString(colID);
            String firstN = result.getString("FIRST_NAME");
            String lastN = result.getString("LAST_NAME");
            String job = result.getString("JOB_TITLE");
            
            //Display the 1st record in the form fields
            txtID.setText(id);
            txtFirstName.setText(firstN);
            txtLastName.setText(lastN);
            txtJobTitle.setText(job);
            
            JOptionPane.showMessageDialog(Workers.this, "Record Deleted!");
                    
        } 
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(Workers.this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_menuInfoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
         String explaniation = "This is my database demo project. "
                + "\nThis project is the same as the non-UI database demo but"
                + "\nwith a User Interface."
                + "\nThe database used is a relational Apache Derby database."
                + "\nThis program will allow you to; cycle through, update,"
                + "\ndelete, and create new records."
                + "\nThis program is to mimmic a simple application that will"
                + "\nmonitor employees in a small buinsess. "
                + "\nIt only covers the; First Name, Last Name, and Job Title."
                + "\nCreator: Paul Laudun, 2016";
        
        JOptionPane.showMessageDialog(Workers.this, explaniation);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanNewRec;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewRec;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSaveNewRec;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJobTitle;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
